service: event-filter

frameworkVersion: '3'
provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: 20201221
  iam:
    role:
      managedPolicies:
        - 'arn:aws:iam::aws:policy/AmazonEventBridgeFullAccess'
  eventBridge:
    useCloudFormation: true

functions:
  <COMPLETE AQUI>