services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=students
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d students -h db"]
      interval: 5s
      timeout: 10s
      retries: 30
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: students
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U admin -d students -h db"]
      interval: 1s
      timeout: 5s
      retries: 10
    restart: always

volumes:
  postgres_data:
